[package]
name = "moon"
version = "0.1.0"
authors = ["wayofthepie <wayofthepie@gmail.com>"]

[dependencies]
nats = "*"
rocket = "0.2.7"
rocket_codegen = "0.2.7"
lazy_static = "0.2.8"
crossbeam = "0.2.10"
